version: '1.0'

services:
  client:
    container_name: monopoly-client
    stdin_open: true
    build:
      context: ./client
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000 # client
    restart: on-failure
    command: npm run start
    depends_on:
      - server
  server:
    container_name: monopoly-server
    build:
      context: ./server
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 5000:5000 # server
    restart: on-failure
    command: npm run start
    depends_on:
      - postgres
    
  postgres:
    container_name: postgres
    stdin_open: true
    image: postgres:12
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 6432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
